name: Python Tests

on:
  # 適用於所有分支的推送與 Pull Request
  push:
  pull_request:
  # 支援手動觸發
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安裝相依套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 執行測試案例
      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
